import { describe, it, expect, beforeEach } from "vitest";
import { runRefreshJob } from "./algorithmic-refresh";
import type { QueryEvaluator, AlgorithmicShelfWriter } from "./algorithmic-refresh";
import type { AlgorithmicQueryDefinition, QueryParams } from "./algorithmic-list";
import { ALGORITHMIC_AUTHOR_LABEL } from "./algorithmic-list";

// ---------------------------------------------------------------------------
// Mocks
// ---------------------------------------------------------------------------

function createMockEvaluator(
  results?: Map<string, string[]>,
): QueryEvaluator & { calls: Array<{ definition: AlgorithmicQueryDefinition; params: Required<QueryParams> }> } {
  const calls: Array<{ definition: AlgorithmicQueryDefinition; params: Required<QueryParams> }> = [];
  return {
    calls,
    async evaluate(definition, params) {
      calls.push({ definition, params });
      const key = `${definition.type}:${params.userId}`;
      const bookIds = results?.get(key) ?? results?.get(definition.type) ?? ["book-1", "book-2"];
      return {
        queryType: definition.type,
        bookIds,
        generatedAt: new Date("2026-05-10T00:00:00Z"),
        userId: params.userId || null,
      };
    },
  };
}

function createMockWriter(): AlgorithmicShelfWriter & {
  calls: Array<Parameters<AlgorithmicShelfWriter["upsert"]>[0]>;
} {
  const calls: Array<Parameters<AlgorithmicShelfWriter["upsert"]>[0]> = [];
  return {
    calls,
    async upsert(input) {
      calls.push(input);
      return { shelfId: `shelf-${input.queryType}` };
    },
  };
}

// ---------------------------------------------------------------------------
// runRefreshJob
// ---------------------------------------------------------------------------

describe("runRefreshJob", () => {
  let evaluator: ReturnType<typeof createMockEvaluator>;
  let writer: ReturnType<typeof createMockWriter>;

  beforeEach(() => {
    evaluator = createMockEvaluator();
    writer = createMockWriter();
  });

  it("evaluates only global queries when no userIds provided", async () => {
    const result = await runRefreshJob(evaluator, writer);

    // Only global queries should fire (new_on_hone, highly_ranked_this_month)
    expect(result.queriesEvaluated).toBe(2);
    expect(result.shelvesUpdated).toBe(2);
    expect(result.errors).toHaveLength(0);

    const evaluatedTypes = evaluator.calls.map((c) => c.definition.type);
    expect(evaluatedTypes).toContain("new_on_hone");
    expect(evaluatedTypes).toContain("highly_ranked_this_month");
    expect(evaluatedTypes).not.toContain("trending_in_circle");
    expect(evaluatedTypes).not.toContain("popular_in_top_genre");
    expect(evaluatedTypes).not.toContain("mutuals_reading_now");
  });

  it("evaluates per-user queries for each provided userId", async () => {
    const result = await runRefreshJob(evaluator, writer, {
      userIds: ["user-a", "user-b"],
    });

    // 2 global + 3 per-user * 2 users = 8
    expect(result.queriesEvaluated).toBe(8);
    expect(result.shelvesUpdated).toBe(8);
    expect(result.errors).toHaveLength(0);
  });

  it("passes correct userId in params for per-user queries", async () => {
    await runRefreshJob(evaluator, writer, {
      userIds: ["user-xyz"],
      queryTypes: ["trending_in_circle"],
    });

    expect(evaluator.calls).toHaveLength(1);
    expect(evaluator.calls[0]!.params.userId).toBe("user-xyz");
  });

  it("writes author label as 'Generated by Hone'", async () => {
    await runRefreshJob(evaluator, writer, {
      queryTypes: ["new_on_hone"],
    });

    expect(writer.calls).toHaveLength(1);
    expect(writer.calls[0]!.authorLabel).toBe(ALGORITHMIC_AUTHOR_LABEL);
    expect(writer.calls[0]!.authorLabel).toBe("Generated by Hone");
  });

  it("writes correct title and description from definition", async () => {
    await runRefreshJob(evaluator, writer, {
      queryTypes: ["new_on_hone"],
    });

    expect(writer.calls[0]!.title).toBe("New on Hone");
    expect(writer.calls[0]!.description).toContain("recently added");
  });

  it("writes null userId for global queries", async () => {
    await runRefreshJob(evaluator, writer, {
      queryTypes: ["new_on_hone"],
    });

    expect(writer.calls[0]!.userId).toBeNull();
  });

  it("writes specific userId for per-user queries", async () => {
    await runRefreshJob(evaluator, writer, {
      queryTypes: ["trending_in_circle"],
      userIds: ["user-42"],
    });

    expect(writer.calls[0]!.userId).toBe("user-42");
  });

  it("filters by queryTypes when specified", async () => {
    const result = await runRefreshJob(evaluator, writer, {
      queryTypes: ["new_on_hone", "highly_ranked_this_month"],
    });

    expect(result.queriesEvaluated).toBe(2);
    const types = evaluator.calls.map((c) => c.definition.type);
    expect(types).toEqual(["new_on_hone", "highly_ranked_this_month"]);
  });

  it("applies param overrides", async () => {
    await runRefreshJob(evaluator, writer, {
      queryTypes: ["new_on_hone"],
      paramOverrides: {
        new_on_hone: { maxItems: 50, windowDays: 7 },
      },
    });

    expect(evaluator.calls[0]!.params.maxItems).toBe(50);
    expect(evaluator.calls[0]!.params.windowDays).toBe(7);
    // defaults preserved for unspecified fields
    expect(evaluator.calls[0]!.params.minThreshold).toBe(3);
  });

  it("captures errors from evaluator without halting other queries", async () => {
    const failingEvaluator: QueryEvaluator = {
      async evaluate(definition, _params) {
        if (definition.type === "new_on_hone") {
          throw new Error("DB timeout");
        }
        return {
          queryType: definition.type,
          bookIds: ["book-1"],
          generatedAt: new Date(),
          userId: null,
        };
      },
    };

    const result = await runRefreshJob(failingEvaluator, writer, {
      queryTypes: ["new_on_hone", "highly_ranked_this_month"],
    });

    expect(result.errors).toHaveLength(1);
    expect(result.errors[0]!.queryType).toBe("new_on_hone");
    expect(result.errors[0]!.error).toBe("DB timeout");
    // The other query still succeeded
    expect(result.shelvesUpdated).toBe(1);
  });

  it("captures errors from writer without halting other queries", async () => {
    const failingWriter: AlgorithmicShelfWriter = {
      async upsert(input) {
        if (input.queryType === "highly_ranked_this_month") {
          throw new Error("Write failed");
        }
        return { shelfId: "shelf-ok" };
      },
    };

    const result = await runRefreshJob(evaluator, failingWriter, {
      queryTypes: ["new_on_hone", "highly_ranked_this_month"],
    });

    expect(result.errors).toHaveLength(1);
    expect(result.errors[0]!.queryType).toBe("highly_ranked_this_month");
    expect(result.shelvesUpdated).toBe(1);
    expect(result.queriesEvaluated).toBe(2);
  });

  it("returns a completedAt timestamp", async () => {
    const before = new Date();
    const result = await runRefreshJob(evaluator, writer);
    const after = new Date();

    expect(result.completedAt.getTime()).toBeGreaterThanOrEqual(before.getTime());
    expect(result.completedAt.getTime()).toBeLessThanOrEqual(after.getTime());
  });

  it("handles empty registry subset gracefully", async () => {
    const result = await runRefreshJob(evaluator, writer, {
      queryTypes: [],
    });

    expect(result.queriesEvaluated).toBe(0);
    expect(result.shelvesUpdated).toBe(0);
    expect(result.errors).toHaveLength(0);
  });

  it("passes bookIds from evaluator to writer", async () => {
    const customEvaluator: QueryEvaluator = {
      async evaluate() {
        return {
          queryType: "new_on_hone",
          bookIds: ["book-a", "book-b", "book-c"],
          generatedAt: new Date(),
          userId: null,
        };
      },
    };

    await runRefreshJob(customEvaluator, writer, {
      queryTypes: ["new_on_hone"],
    });

    expect(writer.calls[0]!.bookIds).toEqual(["book-a", "book-b", "book-c"]);
  });
});
