import { describe, it, expect } from "vitest";
import {
  ALGORITHMIC_QUERY_REGISTRY,
  ALGORITHMIC_AUTHOR_LABEL,
  TRENDING_IN_CIRCLE,
  NEW_ON_HONE,
  HIGHLY_RANKED_THIS_MONTH,
  POPULAR_IN_TOP_GENRE,
  MUTUALS_READING_NOW,
  findQueryDefinition,
  getQueriesByScope,
  validateQueryParams,
  resolveParams,
} from "./algorithmic-list";
import type {
  AlgorithmicQueryDefinition,
  AlgorithmicQueryType,
  QueryParams,
} from "./algorithmic-list";

// ---------------------------------------------------------------------------
// Registry structure
// ---------------------------------------------------------------------------

describe("ALGORITHMIC_QUERY_REGISTRY", () => {
  it("contains exactly 5 launch queries", () => {
    expect(ALGORITHMIC_QUERY_REGISTRY).toHaveLength(5);
  });

  it("has unique query types", () => {
    const types = ALGORITHMIC_QUERY_REGISTRY.map((q) => q.type);
    expect(new Set(types).size).toBe(types.length);
  });

  it("includes the 5 expected query types", () => {
    const types = ALGORITHMIC_QUERY_REGISTRY.map((q) => q.type);
    expect(types).toContain("trending_in_circle");
    expect(types).toContain("new_on_hone");
    expect(types).toContain("highly_ranked_this_month");
    expect(types).toContain("popular_in_top_genre");
    expect(types).toContain("mutuals_reading_now");
  });

  it("all definitions have non-empty title and description", () => {
    for (const def of ALGORITHMIC_QUERY_REGISTRY) {
      expect(def.title.length).toBeGreaterThan(0);
      expect(def.description.length).toBeGreaterThan(0);
    }
  });

  it("all definitions have valid default params", () => {
    for (const def of ALGORITHMIC_QUERY_REGISTRY) {
      expect(def.defaultParams.maxItems).toBeGreaterThan(0);
      expect(def.defaultParams.maxItems).toBeLessThanOrEqual(100);
      expect(def.defaultParams.windowDays).toBeGreaterThanOrEqual(0);
      expect(def.defaultParams.minThreshold).toBeGreaterThanOrEqual(0);
    }
  });
});

// ---------------------------------------------------------------------------
// Author label
// ---------------------------------------------------------------------------

describe("ALGORITHMIC_AUTHOR_LABEL", () => {
  it("is 'Generated by Hone'", () => {
    expect(ALGORITHMIC_AUTHOR_LABEL).toBe("Generated by Hone");
  });
});

// ---------------------------------------------------------------------------
// Individual query definitions
// ---------------------------------------------------------------------------

describe("individual query definitions", () => {
  it("TRENDING_IN_CIRCLE is per-user scoped", () => {
    expect(TRENDING_IN_CIRCLE.scope).toBe("per_user");
    expect(TRENDING_IN_CIRCLE.type).toBe("trending_in_circle");
    expect(TRENDING_IN_CIRCLE.title).toBe("Trending in Your Circle");
  });

  it("NEW_ON_HONE is globally scoped", () => {
    expect(NEW_ON_HONE.scope).toBe("global");
    expect(NEW_ON_HONE.type).toBe("new_on_hone");
    expect(NEW_ON_HONE.title).toBe("New on Hone");
  });

  it("HIGHLY_RANKED_THIS_MONTH is globally scoped", () => {
    expect(HIGHLY_RANKED_THIS_MONTH.scope).toBe("global");
    expect(HIGHLY_RANKED_THIS_MONTH.type).toBe("highly_ranked_this_month");
    expect(HIGHLY_RANKED_THIS_MONTH.title).toBe("Highly Ranked This Month");
  });

  it("POPULAR_IN_TOP_GENRE is per-user scoped", () => {
    expect(POPULAR_IN_TOP_GENRE.scope).toBe("per_user");
    expect(POPULAR_IN_TOP_GENRE.type).toBe("popular_in_top_genre");
    expect(POPULAR_IN_TOP_GENRE.title).toBe("Popular in Your Top Genre");
  });

  it("MUTUALS_READING_NOW is per-user scoped", () => {
    expect(MUTUALS_READING_NOW.scope).toBe("per_user");
    expect(MUTUALS_READING_NOW.type).toBe("mutuals_reading_now");
    expect(MUTUALS_READING_NOW.title).toBe("What Your Mutuals Are Reading Right Now");
  });
});

// ---------------------------------------------------------------------------
// findQueryDefinition
// ---------------------------------------------------------------------------

describe("findQueryDefinition", () => {
  it("returns the definition for a known type", () => {
    const result = findQueryDefinition("trending_in_circle");
    expect(result).toBeDefined();
    expect(result!.type).toBe("trending_in_circle");
    expect(result!.title).toBe("Trending in Your Circle");
  });

  it("returns undefined for an unknown type", () => {
    const result = findQueryDefinition("nonexistent" as AlgorithmicQueryType);
    expect(result).toBeUndefined();
  });

  it("returns each registered definition", () => {
    for (const def of ALGORITHMIC_QUERY_REGISTRY) {
      const found = findQueryDefinition(def.type);
      expect(found).toBe(def);
    }
  });
});

// ---------------------------------------------------------------------------
// getQueriesByScope
// ---------------------------------------------------------------------------

describe("getQueriesByScope", () => {
  it("returns only per_user queries when filtering by per_user", () => {
    const perUser = getQueriesByScope("per_user");
    expect(perUser.length).toBe(3);
    for (const def of perUser) {
      expect(def.scope).toBe("per_user");
    }
  });

  it("returns only global queries when filtering by global", () => {
    const global = getQueriesByScope("global");
    expect(global.length).toBe(2);
    for (const def of global) {
      expect(def.scope).toBe("global");
    }
  });

  it("per_user + global covers all registered queries", () => {
    const perUser = getQueriesByScope("per_user");
    const global = getQueriesByScope("global");
    expect(perUser.length + global.length).toBe(ALGORITHMIC_QUERY_REGISTRY.length);
  });
});

// ---------------------------------------------------------------------------
// validateQueryParams
// ---------------------------------------------------------------------------

describe("validateQueryParams", () => {
  it("returns empty array for valid params", () => {
    const errors = validateQueryParams({ windowDays: 7, maxItems: 20, minThreshold: 2 });
    expect(errors).toHaveLength(0);
  });

  it("returns empty array for empty params (all optional)", () => {
    const errors = validateQueryParams({});
    expect(errors).toHaveLength(0);
  });

  it("reports error for negative windowDays", () => {
    const errors = validateQueryParams({ windowDays: -1 });
    expect(errors).toContain("windowDays must be non-negative");
  });

  it("reports error for maxItems below 1", () => {
    const errors = validateQueryParams({ maxItems: 0 });
    expect(errors).toContain("maxItems must be between 1 and 100");
  });

  it("reports error for maxItems above 100", () => {
    const errors = validateQueryParams({ maxItems: 101 });
    expect(errors).toContain("maxItems must be between 1 and 100");
  });

  it("reports error for negative minThreshold", () => {
    const errors = validateQueryParams({ minThreshold: -1 });
    expect(errors).toContain("minThreshold must be non-negative");
  });

  it("reports multiple errors simultaneously", () => {
    const errors = validateQueryParams({ windowDays: -1, maxItems: 0, minThreshold: -5 });
    expect(errors).toHaveLength(3);
  });

  it("accepts boundary values (windowDays=0, maxItems=1, maxItems=100)", () => {
    expect(validateQueryParams({ windowDays: 0 })).toHaveLength(0);
    expect(validateQueryParams({ maxItems: 1 })).toHaveLength(0);
    expect(validateQueryParams({ maxItems: 100 })).toHaveLength(0);
    expect(validateQueryParams({ minThreshold: 0 })).toHaveLength(0);
  });
});

// ---------------------------------------------------------------------------
// resolveParams
// ---------------------------------------------------------------------------

describe("resolveParams", () => {
  const definition: AlgorithmicQueryDefinition = {
    type: "new_on_hone",
    title: "New on Hone",
    description: "test",
    defaultParams: { userId: "", windowDays: 14, maxItems: 20, minThreshold: 3 },
    scope: "global",
  };

  it("returns defaults when no overrides provided", () => {
    const result = resolveParams(definition);
    expect(result).toEqual(definition.defaultParams);
  });

  it("returns defaults when overrides is undefined", () => {
    const result = resolveParams(definition, undefined);
    expect(result).toEqual(definition.defaultParams);
  });

  it("merges overrides with defaults", () => {
    const result = resolveParams(definition, { maxItems: 50 });
    expect(result.maxItems).toBe(50);
    expect(result.windowDays).toBe(14); // kept default
    expect(result.minThreshold).toBe(3); // kept default
  });

  it("overrides userId for per-user queries", () => {
    const result = resolveParams(definition, { userId: "user-123" });
    expect(result.userId).toBe("user-123");
  });

  it("overrides all params when all are provided", () => {
    const overrides: QueryParams = {
      userId: "user-xyz",
      windowDays: 30,
      maxItems: 10,
      minThreshold: 5,
    };
    const result = resolveParams(definition, overrides);
    expect(result).toEqual(overrides);
  });
});
