/**
 * Algorithmic List Framework
 *
 * Defines a registry of named query definitions that power auto-generated
 * lists such as "Trending in Your Circle", "New on Hone", etc.
 *
 * Each query is a pure declarative definition — no I/O. The runtime
 * (a daily refresh job) evaluates queries against repositories and
 * materializes/updates the corresponding shelf.
 *
 * All algorithmic lists are authored with `authorType: "algorithmic"` and
 * carry the label "Generated by Hone".
 */

import type { EntityId } from "./types";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Supported query types that the refresh job knows how to evaluate.
 */
export type AlgorithmicQueryType =
  | "trending_in_circle"
  | "new_on_hone"
  | "highly_ranked_this_month"
  | "popular_in_top_genre"
  | "mutuals_reading_now";

/**
 * Parameters that scope a query to a specific user context.
 * Not all queries use all fields — e.g., `new_on_hone` is global.
 */
export interface QueryParams {
  /** The viewer/user for whom the list is generated */
  userId?: EntityId;
  /** Time window in days for recency-based queries */
  windowDays?: number;
  /** Maximum items to include in the materialized list */
  maxItems?: number;
  /** Minimum number of events/finishes to qualify */
  minThreshold?: number;
}

/**
 * A single query definition in the registry.
 */
export interface AlgorithmicQueryDefinition {
  /** Unique query type identifier */
  type: AlgorithmicQueryType;
  /** Human-readable title shown to users */
  title: string;
  /** Short description of how the query works */
  description: string;
  /** Default parameters (can be overridden per-user) */
  defaultParams: Required<QueryParams>;
  /** Whether this query is scoped per-user or global */
  scope: "per_user" | "global";
}

/**
 * Result of evaluating an algorithmic query — a list of book IDs
 * in ranked order, ready to be materialized into a shelf.
 */
export interface AlgorithmicQueryResult {
  queryType: AlgorithmicQueryType;
  bookIds: EntityId[];
  generatedAt: Date;
  /** User this was generated for (null for global queries) */
  userId: EntityId | null;
}

/**
 * The author label applied to all algorithmic lists.
 */
export const ALGORITHMIC_AUTHOR_LABEL = "Generated by Hone";

// ---------------------------------------------------------------------------
// Launch Query Definitions (5 queries)
// ---------------------------------------------------------------------------

export const TRENDING_IN_CIRCLE: AlgorithmicQueryDefinition = {
  type: "trending_in_circle",
  title: "Trending in Your Circle",
  description:
    "Books that your mutuals have finished or ranked highly in the past 7 days.",
  defaultParams: {
    userId: "",
    windowDays: 7,
    maxItems: 20,
    minThreshold: 2,
  },
  scope: "per_user",
};

export const NEW_ON_HONE: AlgorithmicQueryDefinition = {
  type: "new_on_hone",
  title: "New on Hone",
  description:
    "Books recently added to the platform that are gaining traction across all users.",
  defaultParams: {
    userId: "",
    windowDays: 14,
    maxItems: 20,
    minThreshold: 3,
  },
  scope: "global",
};

export const HIGHLY_RANKED_THIS_MONTH: AlgorithmicQueryDefinition = {
  type: "highly_ranked_this_month",
  title: "Highly Ranked This Month",
  description:
    "Books with the highest average scores from rankings completed this calendar month.",
  defaultParams: {
    userId: "",
    windowDays: 30,
    maxItems: 20,
    minThreshold: 5,
  },
  scope: "global",
};

export const POPULAR_IN_TOP_GENRE: AlgorithmicQueryDefinition = {
  type: "popular_in_top_genre",
  title: "Popular in Your Top Genre",
  description:
    "The most-finished books in the genre you read most, weighted by recency.",
  defaultParams: {
    userId: "",
    windowDays: 30,
    maxItems: 20,
    minThreshold: 3,
  },
  scope: "per_user",
};

export const MUTUALS_READING_NOW: AlgorithmicQueryDefinition = {
  type: "mutuals_reading_now",
  title: "What Your Mutuals Are Reading Right Now",
  description:
    "Books currently in the 'Reading' shelf of your mutual connections.",
  defaultParams: {
    userId: "",
    windowDays: 0,  // real-time snapshot, no window
    maxItems: 20,
    minThreshold: 1,
  },
  scope: "per_user",
};

// ---------------------------------------------------------------------------
// Query Registry
// ---------------------------------------------------------------------------

/**
 * The query registry: an immutable array of all algorithmic query definitions.
 * Used by the refresh job to iterate and evaluate each query.
 */
export const ALGORITHMIC_QUERY_REGISTRY: readonly AlgorithmicQueryDefinition[] = [
  TRENDING_IN_CIRCLE,
  NEW_ON_HONE,
  HIGHLY_RANKED_THIS_MONTH,
  POPULAR_IN_TOP_GENRE,
  MUTUALS_READING_NOW,
] as const;

// ---------------------------------------------------------------------------
// Registry helpers
// ---------------------------------------------------------------------------

/**
 * Look up a query definition by its type.
 * Returns undefined if the type is not registered.
 */
export function findQueryDefinition(
  type: AlgorithmicQueryType,
): AlgorithmicQueryDefinition | undefined {
  return ALGORITHMIC_QUERY_REGISTRY.find((q) => q.type === type);
}

/**
 * Get all query definitions scoped to a specific scope type.
 */
export function getQueriesByScope(
  scope: "per_user" | "global",
): AlgorithmicQueryDefinition[] {
  return ALGORITHMIC_QUERY_REGISTRY.filter((q) => q.scope === scope);
}

/**
 * Validate that query params are within acceptable ranges.
 * Returns an array of error messages (empty = valid).
 */
export function validateQueryParams(params: QueryParams): string[] {
  const errors: string[] = [];

  if (params.windowDays !== undefined && params.windowDays < 0) {
    errors.push("windowDays must be non-negative");
  }
  if (params.maxItems !== undefined && (params.maxItems < 1 || params.maxItems > 100)) {
    errors.push("maxItems must be between 1 and 100");
  }
  if (params.minThreshold !== undefined && params.minThreshold < 0) {
    errors.push("minThreshold must be non-negative");
  }

  return errors;
}

/**
 * Merge user-provided params with the definition's defaults.
 */
export function resolveParams(
  definition: AlgorithmicQueryDefinition,
  overrides?: QueryParams,
): Required<QueryParams> {
  if (!overrides) return definition.defaultParams;

  return {
    userId: overrides.userId ?? definition.defaultParams.userId,
    windowDays: overrides.windowDays ?? definition.defaultParams.windowDays,
    maxItems: overrides.maxItems ?? definition.defaultParams.maxItems,
    minThreshold: overrides.minThreshold ?? definition.defaultParams.minThreshold,
  };
}
